version: "3"
services:
  web:
    build: .
    environment:
      PG_USER: morah
      PG_PASSWORD: morah
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: morah
      POSTGRES_PASSWORD: morah
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  